#!/bin/bash

NVIM_LOCATION=$(which nvim)

if ! [ -e /usr/local/bin/vi ]; then ln -s $NVIM_LOCATION /usr/local/bin/vi; fi

if ! [ -e /usr/local/bin/vim ]; then ln -s $NVIM_LOCATION /usr/local/bin/vim; fi

if ! [ -e /usr/local/bin/view ]; then ln -s $NVIM_LOCATION /usr/local/bin/view; fi

